blank_issues_enabled: true
contact_links:
  - name: TricklePay Documentation
    url: https://github.com/TricklePay/tricklepay-frontend#readme
    about: Please consult the TricklePay documentation and README before opening an issue.
